export const LOGGED_IN = 'LOGGED_IN';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_QUESTION_INDEX = 'UPDATE_QUESTION_INDEX';